/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gradle_interfaces;
import java.util.ArrayList;
import java.util.Scanner;
public class App {

    public static void main(String[] args) {
        int whichOne;
        int howManyObjects;
        ArrayList<Publishing> libraryObjects = new ArrayList<>();
        fillArray(libraryObjects);
        showResults(libraryObjects);
    }
    public static void showResults(ArrayList listToShow){
        System.out.println("These are the results: ");
        listToShow.stream().map(x->x.toString()).forEach(System.out::println);
    }
    public static void fillArray(ArrayList listToFill){
        int amountOfObjects = readAmount();
        int whichOne;
        String code;
        String title;
        int year;
        int journalNumber;

        for(int i = 0;i<amountOfObjects;i++){
            Scanner scanProperties = new Scanner(System.in);
            whichOne = bookOrJournal();
            System.out.print("\nWhat is the code: ");
            code = scanProperties.nextLine();
            System.out.print("\nWhat is the title: ");
            title = scanProperties.nextLine();
            System.out.print("\nThe year of publication is: ");
            year = scanProperties.nextInt();

            if(whichOne == 0){
                Book currentObject = new Book(code,title,year);
                System.out.println("Do you want to Lent this book? (1 = yes, 0 = no");
                if((scanProperties.nextInt())==1) currentObject.toLend();
                listToFill.add(currentObject);
            }
            else{
                System.out.println("What is the number of the Journal?");
                journalNumber = scanProperties.nextInt();
                Journal currentObject = new Journal(code,title,year,journalNumber);
                listToFill.add(currentObject);
            }
        }

    }
    public static int readAmount(){
        Scanner scanAmount = new Scanner(System.in);
        System.out.println("How many objects are you going to create?");
        int amount = scanAmount.nextInt();
        return amount;
    }
    public static int bookOrJournal(){
        int kindOfPublication;
        Scanner dataInput = new Scanner(System.in);
        System.out.println("What kind of publication is it? (0 = Book, 1 = Journal)");
        kindOfPublication = dataInput.nextInt();
        return kindOfPublication;
    }
}
